### ISSUE TITLE
Request for clarification on the Bloom Filter Trie library

### ISSUE THREAD

**Issue by GenGrim76** [GuillaumeHolley/BloomFilterTrie#17]
Hi, I'm Gennaro Grimaudo, second year student of the PhD course in ICT of the Department of Computer Engineering of the University of Palermo. I collaborate in a research project entitled "Succinct Data Structures for Open Data" under the supervision of Prof. Raffaele Giancarlo (Department of Mathematics and Computer Science).

I just got interested in your Bloom Filter Trie library.

I have a question for you, to which I hope you can provide me with some valuable information.

I ran the ./bft script with the build option, with a k value not a 9-multiple, and it gave me an error message about the k length not allowed.

Can it work for an arbitrary k value?

Thanks for your time.

With regard,
Gennaro

**Comment by GuillaumeHolley** [comment]
Hi @GenGrim76,

The Bloom Filter Trie library is restricted to k-mer sizes which are a multiple of length 9 so it wouldn't work for arbitrary k-mer sizes. To make it work for arbitrary kmer sizes, you would have to round up your k-mer size to the nearest multiple of 9 and suffix your input k-mers with some arbitrary bases (for padding purposes).

In theory, the data structure itself has no such restrictions and could work for arbitrary values. However, the BFT library was my PhD thesis first project and it was developed initially as a proof-of-concept. In order to get it done within the timeline of my PhD candidacy, we imposed some technical limitations on this proof-of-concept such as this multiple of 9. Ultimately, the interest in the BFT implementation grew and I had no time to remove these limitations nor to make another proper implementation so the proof-of-concept became a library with these restrictions. I had some plans for a new C++ library, recoded from scratch, including multithreading, deletion operations and arbitrary kmer sizes but never found the time to complete the project. Even though the BFT is an excellent data structure, I would strongly advise against using the present library in any project.

Guillaume

**Comment by GenGrim76** [comment]
Thank You for those clarification.

Regards, 
Gennaro
