### ISSUE TITLE
Non-reproducible seqfaults

### ISSUE THREAD

**Issue by Phelimb** [GuillaumeHolley/BloomFilterTrie#4]
I have been trying to build a BFT for ~1000 samples of Ecoli. 

The first time I tried to load all 1000 samples using `build` and `bft` segfaulted on sample 730. 

```
File 730: ERR583553.txt

1000192 kmers read
2000128 kmers read
3000064 kmers read
4000000 kmers read
5000192 kmers read

Elapsed time: 58.843062 s
Total elapsed time: 27967.155125 s
Peak of memory: 1
```

I then reran on 729 samples but `bft` segfaulted on sample 713

```
File 713: ERR440759.txt

1000192 kmers read
2000128 kmers read
3000064 kmers read
4000000 kmers read
5000192 kmers read

Elapsed time:

```

Any suggestions on how to try and debug this?

**Comment by GuillaumeHolley** [comment]
Hi Phelim,

hum... that's very annoying, it's difficult to say as a first guess where the bug could come from and from what you wrote, the bug seems to appear randomly which is not helping. So there is probably an unauthorized memory access somewhere.
The only way to debug this is to run Valgrind on it, which might take a while but hopefully, the error does not only occur at the end of the insertion.

What about you send me by e-mail which dataset you are using, which tool/command you use to generate the k-mers / run the bft and I try to figure out what's wrong?

Guillaume

**Comment by GuillaumeHolley** [comment]
Hi Phelim,

You might have noticed that we released a new version few weeks ago in which we refactored a lot of code and fixed a couple of bugs. Hopefully, this new version solves the problem you've been encountering ;)

Guillaume

**Comment by Phelimb** [comment]
Thanks Guillaume, 

Sorry for not getting back to you before. I'll try out the new version. 👍 

I'll close this for now and reopen if I can reproduce in the new version.

Phelim
