### ISSUE TITLE
jemalloc-problems and unable to read list-file

### ISSUE THREAD

**Issue by UEWiebelitz** [GuillaumeHolley/BloomFilterTrie#5]
Hello,

we tried to start the application with the following command:
./bft build 27 ./list myOut

the file ./list has following content:
~/Downloads/Homo_sapiens.GRCh38.dna_rm.toplevel.fa Human

Unfortunately the program exited with following output:
<jemalloc>: Invalid conf pair: lg_dirty_mult:8
<jemalloc>: Invalid conf pair: lg_chunk:22
Invalid list_genome_files.

Is there anything wrong with our list-file?
Is there any more detailed information about the expected structure?

Thank you in advance!

**Comment by GuillaumeHolley** [comment]
Hi there :)

So it seems there are two problems here: one with Jemalloc and one with your input.

The content of your file named _list_ seems to be the name of a FASTA file, then a space character and then, the word "Human". A first problem here is that this file must only contain one _path/filename_ per line, nothing else. An example of the content of such a file would be:

```
repository_1/my_file_1.ext
repository_2/sub_repository_2/my_file_2.ext
```

Furthermore, the BFT binary does not accept as input FASTA or FASTQ files. Instead, the BFT binary takes as input files containing the k-mers that you want to insert into the BFT. Each of these files contains one k-mer (plain text) per line, eventually followed by a space character and a number (such as a count). Such files can be obtained using a k-mer counting software such as  DSK (https://github.com/GATB/dsk) or KMC3 (https://github.com/refresh-bio/KMC) in which you input your FASTA file.

Regarding the Jemalloc lines: 

```
: Invalid conf pair: lg_dirty_mult:8
: Invalid conf pair: lg_chunk:22
```

i am not sure what is going on here, it seems Jemalloc does not accept the configuration I am providing it but I never had such problem before. Can you make sure that Jemalloc is correctly installed and that the header file _jemalloc.h_  is present on your system?

Also, could you provide me the following information:
- Version of Jemalloc you have installed
- Are you running the BFT on a laptop, a cluster or a desktop computer?
- What is the Operating System you a running the BFT with?

A quick hotfix would be to replace the custom configuration of Jemalloc by the default one. For this, you need to comment out the following line in the file _src/main.c_:

```
const char* malloc_conf = "narenas:1,tcache:false,lg_dirty_mult:8,lg_chunk:22";
```

You can do this by replacing it with:

```
//const char* malloc_conf = "narenas:1,tcache:false,lg_dirty_mult:8,lg_chunk:22";
```

Then, recompile the binary. This should do the trick but you won't obtain with this quick fix the best performance out of the BFT.

Please let me know how it goes :)

Guillaume

**Comment by UEWiebelitz** [comment]
Hi,

thank you for your quick reply!
Thanks for the hints regarding the input-file! Granted, we
misinterpreted following part of the ReadMe: one path and name per line.

Is the jemalloc-Error directly related to the input-problems? If so, we
maybe should try this before searching for nothing ;-)
If not, here are some Information:
The version-number of jemalloc is: 1:5.0.1-3
Yes, we are currently running it on a laptop with 16GB RAM.
The used operating system is Arch-Linux (64Bit).

We'll let you know, when we had a chance to build our k-mers (this does
not seem to work on such a small machine for human genomes) ;-)

Kind regards and thanks again!
 Elias

**Comment by GuillaumeHolley** [comment]
Hi Elias

So I am 100% positive that the Jemalloc problem is not related to your input problem :) As a matter of fact, I just realized that the Jemalloc version you are using is very recent -version 5 was released on June 23rd, so 3 weeks ago- and it is most likely that this new version does not accept a custom configuration like the one I am using with the BFT. It kind of sucks because it was perfectly compatible with previous versions of Jemalloc but anyway, there is probably a new way to do this so this issue should be fixed soon.

In the meantime, I would advise you to simply install Jemalloc version 4 instead of version 5 and the BFT will run smoothly :)

Regarding the k-mers construction, DSK and KMC3 are both disk-based software which are extremely memory and time efficient, you can basically specify in their options the amount of RAM you want them to use. 16 GB of RAM is way more than enough to count k-mers for very large read files, including human genome read files.

**Comment by UEWiebelitz** [comment]
Hi Guillaume,


here a little update:
After some attempts we found valid input-arguments and we could build
the trie.
Of course we could have avoided this trouble by reading the docs more
attentive :-)

Thank you very much for your support!

Best regards
 Elias
